### Making a Matrix in using NumPy

In [2]:
import numpy as np

my_matrix = np.array([[1, 2, 3], 
                      [4, 5, 6]])

print("My matrix:\n", my_matrix)

My matrix:
 [[1 2 3]
 [4 5 6]]


### Adding Two Matrices

In [3]:
matrix1 = np.array([[1, 2], 
                    [3, 4]])
matrix2 = np.array([[5, 6], 
                    [7, 8]])

sum_matrix = matrix1 + matrix2
print("Sum of matrices:\n", sum_matrix)

Sum of matrices:
 [[ 6  8]
 [10 12]]


### Matrix Multiplication

In [4]:
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1,end="\n======================\n")
print("Matrix 2:\n", matrix2, end="\n======================\n")
print("Result of matrix multiplication:\n", result, end="\n======================\n")

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Result of matrix multiplication:
 [[19 22]
 [43 50]]


### Excercise: Find the Inverse of a Matrix

**Question**:  
Find the inverse of the function that computes the inverse of the given 2x2 matrix:  

\begin{pmatrix} 4 & 7 \\ 2 & 6 \end{pmatrix}


Do **not** use any built-in inverse functions. Instead, use the formula for the inverse of a 2x2 matrix:  

$$\text{If } A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}, \quad \text{then } A^{-1} = \frac{1}{ad - bc} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$$



In [9]:
matrix = np.array([[4,7],
                   [2,6]])

In [10]:
def matrix_inverse(matrix):

    a, b = matrix[0]
    c, d = matrix[1]
    determinant = a * d - b * c
    if determinant == 0:
        print("Matrix is singular and cannot be inverted.")
        return None
    inverse_matrix = (1 / determinant) * np.array([[d, -b], 
                                                    [-c, a]])
    return inverse_matrix

### Inverse using My Function

In [11]:
print("Matrix Inverse: \n", matrix_inverse(matrix))

Matrix Inverse: 
 [[ 0.6 -0.7]
 [-0.2  0.4]]


### Comparing Inverse With NumPy's Inverse Function

In [12]:
print("Matrix Inverse: \n", np.linalg.inv(matrix))

Matrix Inverse: 
 [[ 0.6 -0.7]
 [-0.2  0.4]]
